### ISSUE TITLE
The DockerSlim is not working 

### ISSUE THREAD

**Issue by dshamanthreddy** [quickbooks2018/aws#1]
I have pulled an image using this repo ,and then try to docker-slim build the image, but I get below error

time="2022-10-02T22:29:05-04:00" level=fatal msg="docker-slim: failure" error="API error (400): failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"/opt/dockerslim/bin/docker-slim-sensor\": stat /opt/dockerslim/bin/docker-slim-sensor: no such file or directory: unknown" stack="goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x64\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailOn({0x101188a00, 0x140006b6900})\n\tgithub.com/docker-slim/docker-slim/pkg/util/errutil/errutil.go:28 +0x38\ngithub.com/docker-slim/docker-slim/pkg/app.(*ExecutionContext).FailOn(0x14000120000?, {0x101188a00?, 0x140006b6900?})\n\tgithub.com/docker-slim/docker-slim/pkg/app/execontext.go:56 +0x44\ngithub.com/docker-slim/docker-slim/pkg/app/master/commands/build.OnCommand(_, _, {_, _}, _, _, _, _, _, _, ...)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/commands/build/handler.go:1063 +0x4e34\ngithub.com/docker-slim/docker-slim/pkg/app/master/commands/build.glob..func1(0x140005707c0)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/commands/build/cli.go:694 +0x3c88\ngithub.com/urfave/cli/v2.(*Command).Run(0x101747ba0, 0x140005505c0)\n\tgithub.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4fc\ngithub.com/urfave/cli/v2.(*App).RunContext(0x14000582820, {0x1011904d0?, 0x1400009c008}, {0x140000a4000, 0x7, 0x7})\n\tgithub.com/urfave/cli/v2@v2.3.0/app.go:313 +0x860\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\tgithub.com/urfave/cli/v2@v2.3.0/app.go:224\ngithub.com/docker-slim/docker-slim/pkg/app/master.Run()\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/app.go:15 +0x4c\nmain.main()\n\tgithub.com/docker-slim/docker-slim/cmd/docker-slim/main.go:15 +0x1c4\n" version="darwin|Transformer|1.38.0|latest|latest

<img width="760" alt="Screen Shot 2022-10-02 at 11 20 45 PM" src="https://user-images.githubusercontent.com/18470551/193495830-7dd1ebfc-3ada-42e0-a1fe-e564be03737a.png">

**Comment by quickbooks2018** [comment]
--http-probe=false
